spring:
  application:
    name: netflix-client

management:
  port: 8081
  context-path: /admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health

info:
  team:
    developer: Wang Zhizhao
    tester: Wang Zhizhao
  docs:
    url: https://github.com/wzz-code/cloud-netflix-sample

endpoints:
  sensitive: false
  beans:
    sensitive: true